### PR TITLE
[BUGFIX] catch API exception to prevent Scheduler error

### LINKED ISSUE #18: [BUG] Scheduler error "Media is permanently deleted"
**Describe the bug**

See screen shot. Could this be related to changed publish sites? Report from client: "We downloaded images from different "publish sites" because we changed the option during our testing. Or to be more precise, one publish site and without any publish site set. I hope that does not have any influence? Apart from that we configured the extension according and functional to the description."

**To Reproduce**

More info needed.

**Expected behavior**

**Screenshots**

qbank_task_updateqbankfilestatuscommand

**Desktop (please complete the following information):**

n/a

**Smartphone (please complete the following information):**

n/a

**Additional context**

n/a

### PR DESCRIPTION
**Pull request by pixelmatseriks**
Adds a new status "remote is deleted" field for sys_file table, so need to Analyze Database.
If exception is thrown when fetching media from API, this field will set to true.
This will prevent file from beeing processed in any of the conslole commands.
Also sync buttons in backend module will be removed.

Fixes #18.

# New Pull Request checklist

## PR Type

What kind of change does this PR introduce?

- [ ] [FEATURE] - A new feature
- [x] [BUGFIX] - A bug fix
- [ ] [TASK] - Any task, which is not a **new feature** or **bugfix**
- [ ] [TEST] - Adding missing tests
- [ ] [DOC] - Documentation only changes
- [ ] [WIP] - Work in progress tag, should not be present when creating pull requests

## Breaking change

Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: Classes/Utility/QbankUtility.php [hunk 1]
```diff
@@ -164,4 +165,19 @@ public static function getAutoUpdateOption(): int
...
+
+    /**
+     * Returns true if request exception seems to be due to that the media is permanently deleted in QBank.
+     *
+     * @param RequestException $re
+     * @return bool
+     */
+    public static function qbankRequestExceptionStatesMediaIsDeleted(RequestException $re): bool
+    {
+        if (strpos(strtolower($re->getMessage()), 'media is permanently deleted') > 0) {
```
Comment (mabolek) [inline Classes/Utility/QbankUtility.php:177]: Oh, this is so ugly, but I can't think of a better way either.

File: Classes/Service/QbankService.php [hunk 2]
```diff
@@ -234,7 +236,19 @@ public function synchronizeMetadata(int $fileId): void
...
 
-        $qbankRecord = $this->mediaRepository->findById($qbankId);
+        try {
+            /** @var MediaResponse $qbankRecord */
+            $qbankRecord = $this->mediaRepository->findById($qbankId);
+        } catch (RequestException $re) {
+            if (QbankUtility::qbankRequestExceptionStatesMediaIsDeleted($re)) {
+                $this->updateFileRemoteIsDeleted($fileId);
+
+                throw new \TYPO3\CMS\Core\Resource\Exception\FileDoesNotExistException(
```
Comment (mabolek) [inline Classes/Service/QbankService.php:246]: I think we need our own exception here. This exception is related to files in FAL, so it's not applicable to QBank.

**Review by mabolek — CHANGES_REQUESTED** [review]
Why is this marked as breaking? I can't see the breaking change.

A couple of small suggestions. Check comments.

File: Classes/Utility/QbankUtility.php (hunk 1 above)
Comment (pixelmatseriks) [reply Classes/Utility/QbankUtility.php:177]: yes, I now :smile:
