### PR TITLE
[BUGFIX] hide button if no more images can be added to field, resolves #6

### LINKED ISSUE #6: [BUG] Select button still displayed if maxitems has been reached
**Describe the bug**
There is no reaction of the QBank button for TCA maxitems definition. We have e.g. for page resources an limit for only one image resource. ($GLOBALS['TCA']['pages']['columns']['media']['config']['maxitems'] = 1;). Your extension do not react on this and the button will still be diplayed if an image is already in use. See attachment qbank-2

**Screenshots**
qbank-2

### PR DESCRIPTION
**Pull request by pixelmatseriks**
# New Pull Request checklist

## PR Type

What kind of change does this PR introduce?

- [ ] [FEATURE] - A new feature
- [x] [BUGFIX] - A bug fix
- [ ] [TASK] - Any task, which is not a **new feature** or **bugfix**
- [ ] [TEST] - Adding missing tests
- [ ] [DOC] - Documentation only changes
- [ ] [WIP] - Work in progress tag, should not be present when creating pull requests

## Breaking change

Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: Classes/FormEngine/Container/QbankSelectorButtonContainer.php [hunk 1]
```diff
@@ -189,4 +190,37 @@ protected function getExtensionConfigurationManager(): ExtensionConfigurationMan
...
+                $numberOfFullLocalizedChildren++;
+            }
+        }
+
+        if ($isReadOnly || $numberOfFullLocalizedChildren >= $config['maxitems']) {
+            $inlineStyle[] = 'display: none';
+        }
+
+        if (count($inlineStyle) > 0) {
+            return 'style="' . implode(';', $inlineStyle) . '"';
```
Comment (mabolek) [inline Classes/FormEngine/Container/QbankSelectorButtonContainer.php:221]: I think `$inlineStyles` (plural) is better for an array. I don't know what `$numberOfFullLocalizedChildren` really counts, but I imagine it's either "filled" (i.e. populated) or "fully" (i.e. completely) localized children.

```suggestion
        $inlineStyles = [];
        $parameterArray = $this->data['parameterArray'];

        $config = $parameterArray['fieldConf']['config'];
        $isReadOnly = isset($config['readOnly']) && $config['readOnly'];

        $numberOfFullyLocalizedChildren = 0;
        foreach ($parameterArray['fieldConf']['children'] as $child) {
            if (!$child['isInlineDefaultLanguageRecordInLocalizedParentContext']) {
                $numberOfFullyLocalizedChildren++;
            }
        }

        if ($isReadOnly || $numberOfFullyLocalizedChildren >= $config['maxitems']) {
            $inlineStyles[] = 'display: none';
        }

        if (count($inlineStyles) > 0) {
            return 'style="' . implode(';', $inlineStyles) . '"';
```

**Review by mabolek — APPROVED** [review]
